#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Rebuild the identical 8000-face scene, restore the user-accepted V2 state at
# source frame 583, replay the short 584--619 warm-up, then record fold three.
# The semantic waist-center analysis places the corrected close at about
# world (0.50, -0.245). During placement the right gripper levels only after
# the flap is airborne so the fold arrives broadside instead of vertically.
CHECKPOINT_MODE=load \
CHECKPOINT_FILE="${CHECKPOINT_FILE:-$PROJECT_ROOT/outputs/episode_000000/checkpoints/g3_second_fold_arc100_stack100_8000f_v2.pkl}" \
RUN_LABEL="${RUN_LABEL:-g12_third_fold_v2_release_retreat90_8000f}" \
ARC_MESH_FACES="${ARC_MESH_FACES:-8000}" \
DEMO_FRAMES="${DEMO_FRAMES:-946}" \
TABLE_FRICTION=1.0 \
FIRST_FOLD_STACK_OVERLAP=-0.015 \
SECOND_FOLD_TRANSPORT_LIFT=0.000 \
SECOND_FOLD_ROLL_ARC_HEIGHT=0.100 \
SECOND_FOLD_ROLL_PATH=staged \
SECOND_FOLD_PLACEMENT_RELAX=0.060 \
SECOND_FOLD_PLACEMENT_LIFT="${SECOND_FOLD_PLACEMENT_LIFT:-0.000}" \
SECOND_FOLD_STACK_OVERLAP=0.100 \
THIRD_FOLD_GRASP_DEPTH="${THIRD_FOLD_GRASP_DEPTH:-0.005}" \
THIRD_FOLD_GRASP_LATERAL="${THIRD_FOLD_GRASP_LATERAL:-0.012}" \
THIRD_FOLD_GRASP_WORLD_X="${THIRD_FOLD_GRASP_WORLD_X:--0.095}" \
THIRD_FOLD_GRASP_WORLD_Y="${THIRD_FOLD_GRASP_WORLD_Y:--0.055}" \
THIRD_FOLD_LIFT="${THIRD_FOLD_LIFT:-0.040}" \
THIRD_FOLD_OUTWARD_PULL_CANCEL="${THIRD_FOLD_OUTWARD_PULL_CANCEL:-0.000}" \
THIRD_FOLD_PLACEMENT_DEPTH="${THIRD_FOLD_PLACEMENT_DEPTH:-0.000}" \
THIRD_FOLD_TOP_OFFSET="${THIRD_FOLD_TOP_OFFSET:-0.110}" \
THIRD_FOLD_PLACEMENT_LEVEL="${THIRD_FOLD_PLACEMENT_LEVEL:-0.000}" \
THIRD_FOLD_FRONT_PLANE_ROLL_DEG="${THIRD_FOLD_FRONT_PLANE_ROLL_DEG:-0.000}" \
THIRD_FOLD_RELEASE_HOLD="${THIRD_FOLD_RELEASE_HOLD:-1}" \
POST_RELEASE_OPEN_HOLD_FRAMES="${POST_RELEASE_OPEN_HOLD_FRAMES:-10}" \
POST_RELEASE_RETREAT_FRAMES="${POST_RELEASE_RETREAT_FRAMES:-40}" \
POST_RELEASE_RETREAT_HEIGHT="${POST_RELEASE_RETREAT_HEIGHT:-0.090}" \
POST_RELEASE_RETREAT_TOP_OFFSET="${POST_RELEASE_RETREAT_TOP_OFFSET:-0.000}" \
POST_RELEASE_SETTLE_FRAMES="${POST_RELEASE_SETTLE_FRAMES:-120}" \
  "$PROJECT_ROOT/run_three_folds_arc.sh" "$@"
