#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_ROOT="${OUTPUT_ROOT:-$PROJECT_ROOT/outputs/episode_000000}"

# Full-process reproducibility run for the manually accepted G3 V2 setup:
# 8k cloth, fast IPC solver, collision-safe wrist/palm proxy geometry, and the
# accepted first/second-fold trajectory corrections.  The current third-fold
# release/retreat tail is retained so the complete demo can be inspected.
FAST_PREVIEW=1 \
GENESIS_GPU="${GENESIS_GPU:-GPU-573ea767-dda1-d1a3-84e3-aa0b5697120c}" \
SHIRT_OBJ="$OUTPUT_ROOT/assets/short-shirt-8000f.obj" \
ROBOT_URDF="${ROBOT_URDF:-$PROJECT_ROOT/assets/acone_ipc/acone_ipc.urdf}" \
CHECKPOINT_MODE="${CHECKPOINT_MODE:-save}" \
CHECKPOINT_FILE="${CHECKPOINT_FILE:-$OUTPUT_ROOT/checkpoints/g3v2_full_fast_8000_pre_third.pkl}" \
RUN_LABEL="${RUN_LABEL:-g3v2_full_fast_8000_reproduction}" \
ARC_MESH_FACES=8000 \
DEMO_FRAMES="${DEMO_FRAMES:-946}" \
SHOW_VIEWER="${SHOW_VIEWER:-1}" \
CONTACT_D_HAT="${CONTACT_D_HAT:-0.002}" \
SETTLE_FRAMES="${SETTLE_FRAMES:-60}" \
FIRST_GRASP_CLEARANCE_LIFT="${FIRST_GRASP_CLEARANCE_LIFT:-0.040}" \
TABLE_FRICTION="${TABLE_FRICTION:-1.0}" \
FIRST_FOLD_STACK_OVERLAP="${FIRST_FOLD_STACK_OVERLAP:--0.015}" \
SECOND_FOLD_TRANSPORT_LIFT="${SECOND_FOLD_TRANSPORT_LIFT:-0.000}" \
SECOND_FOLD_ROLL_ARC_HEIGHT="${SECOND_FOLD_ROLL_ARC_HEIGHT:-0.040}" \
SECOND_FOLD_ROLL_PATH="${SECOND_FOLD_ROLL_PATH:-smooth_arc}" \
SECOND_FOLD_PLACEMENT_RELAX="${SECOND_FOLD_PLACEMENT_RELAX:-0.060}" \
SECOND_FOLD_STACK_OVERLAP="${SECOND_FOLD_STACK_OVERLAP:-0.100}" \
THIRD_FOLD_GRASP_DEPTH="${THIRD_FOLD_GRASP_DEPTH:-0.005}" \
THIRD_FOLD_GRASP_LATERAL="${THIRD_FOLD_GRASP_LATERAL:-0.012}" \
THIRD_FOLD_GRASP_WORLD_X="${THIRD_FOLD_GRASP_WORLD_X:--0.095}" \
THIRD_FOLD_GRASP_WORLD_Y="${THIRD_FOLD_GRASP_WORLD_Y:--0.055}" \
THIRD_FOLD_LIFT=0.040 \
THIRD_FOLD_OUTWARD_PULL_CANCEL=0.000 \
THIRD_FOLD_PLACEMENT_DEPTH=0.000 \
THIRD_FOLD_TOP_OFFSET=0.110 \
THIRD_FOLD_PLACEMENT_LEVEL=0.000 \
THIRD_FOLD_FRONT_PLANE_ROLL_DEG=0.000 \
THIRD_FOLD_RELEASE_HOLD=1 \
POST_RELEASE_OPEN_HOLD_FRAMES="${POST_RELEASE_OPEN_HOLD_FRAMES:-10}" \
POST_RELEASE_RETREAT_FRAMES="${POST_RELEASE_RETREAT_FRAMES:-40}" \
POST_RELEASE_RETREAT_HEIGHT="${POST_RELEASE_RETREAT_HEIGHT:-0.090}" \
POST_RELEASE_RETREAT_TOP_OFFSET="${POST_RELEASE_RETREAT_TOP_OFFSET:-0.000}" \
POST_RELEASE_SETTLE_FRAMES="${POST_RELEASE_SETTLE_FRAMES:-120}" \
  "$PROJECT_ROOT/run_three_folds_arc.sh" "$@"
