#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_ROOT="${OUTPUT_ROOT:-$PROJECT_ROOT/outputs/episode_000000}"

# Reproduce the 2026-08-17 major-fix validation from the initial cloth state:
# - third-fold target stays above the table through close;
# - release hold keeps one continuous arm IK branch through frame 979;
# - source finger commands remain active, so the right gripper really opens.
FAST_PREVIEW=1 \
GENESIS_GPU="${GENESIS_GPU:-GPU-573ea767-dda1-d1a3-84e3-aa0b5697120c}" \
SHIRT_OBJ="$OUTPUT_ROOT/assets/short-shirt-8000f.obj" \
ROBOT_URDF="${ROBOT_URDF:-$PROJECT_ROOT/assets/acone_ipc/acone_ipc.urdf}" \
CHECKPOINT_MODE="${CHECKPOINT_MODE:-off}" \
RUN_LABEL="${RUN_LABEL:-g3v2_full_majorfix_8000}" \
ARC_MESH_FACES=8000 \
DEMO_FRAMES="${DEMO_FRAMES:-980}" \
SUBSTEPS="${SUBSTEPS:-2}" \
SHOW_VIEWER="${SHOW_VIEWER:-0}" \
VISUALIZE_IPC_PROXIES="${VISUALIZE_IPC_PROXIES:-1}" \
RENDER_IPC_ACTUAL_VISUALS="${RENDER_IPC_ACTUAL_VISUALS:-1}" \
IPC_CONSTRAINT_STRENGTH_TRANSLATION="${IPC_CONSTRAINT_STRENGTH_TRANSLATION:-300}" \
IPC_CONSTRAINT_STRENGTH_ROTATION="${IPC_CONSTRAINT_STRENGTH_ROTATION:-1000}" \
IPC_RIGID_RIGID_CONTACT=1 \
CONTACT_D_HAT=0.002 \
SETTLE_FRAMES=60 \
TABLE_FRICTION=1.0 \
FIRST_GRASP_CLEARANCE_LIFT=0.040 \
FIRST_FOLD_TCP_LIFT=0.015 \
FIRST_FOLD_TRANSFER_LIFT=0.050 \
FIRST_FOLD_STACK_OVERLAP=-0.015 \
SECOND_FOLD_TRANSPORT_LIFT=0.000 \
SECOND_FOLD_ROLL_ARC_HEIGHT=0.040 \
SECOND_FOLD_ROLL_PATH=smooth_arc \
SECOND_FOLD_PLACEMENT_RELAX=0.060 \
SECOND_FOLD_PLACEMENT_LIFT=0.000 \
SECOND_FOLD_STACK_OVERLAP=0.125 \
SECOND_FOLD_CORRECTION_RELEASE_START=600 \
SECOND_FOLD_CORRECTION_RELEASE_END=619 \
THIRD_FOLD_GRASP_DEPTH=0.005 \
THIRD_FOLD_GRASP_LATERAL=0.012 \
THIRD_FOLD_GRASP_WORLD_X=-0.051 \
THIRD_FOLD_GRASP_WORLD_Y=-0.085 \
THIRD_FOLD_LIFT=0.040 \
THIRD_FOLD_OUTWARD_PULL_CANCEL=0.000 \
THIRD_FOLD_PLACEMENT_DEPTH=0.000 \
THIRD_FOLD_TOP_OFFSET=0.110 \
THIRD_FOLD_PLACEMENT_LEVEL=0.000 \
THIRD_FOLD_FRONT_PLANE_ROLL_DEG=0.000 \
THIRD_FOLD_SMOOTH_ROTATION="${THIRD_FOLD_SMOOTH_ROTATION:-1}" \
THIRD_FOLD_RELEASE_HOLD=1 \
POST_RELEASE_OPEN_HOLD_FRAMES=0 \
POST_RELEASE_RETREAT_FRAMES=0 \
POST_RELEASE_RETREAT_HEIGHT=0 \
POST_RELEASE_RETREAT_TOP_OFFSET=0 \
POST_RELEASE_SETTLE_FRAMES=0 \
  "$PROJECT_ROOT/run_three_folds_arc.sh" "$@"
